name: Build
on: [push, pull_request]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PODCAST_URL: ${{secrets.PODCAST_URL}}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        experimental: [false]
        include:
        - node: 15.x
          experimental: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js (NPMJS) ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm test
#    - name: create env file
#      run: |
#        touch .env
#        echo PODCAST_URL=${{ secrets.PODCAST_URL }} >> .env
    - name: Set environment variable
      id: podcast_url
      run: echo "PODCAST_URL=${{ secrets.PODCAST_URL }}" >> $GITHUB_ENV
    - name: Build
      run: npm run build
      continue-on-error: true
    - name: Code coverage reporting
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./js-coverage/lcov.info
      continue-on-error: true
